docs/DeveloperGuide.md

Updated glossary for JARVIS.
Resolves #23.

Update glossary for DeveloperGuide

---

docs/UserGuide.md

Update UserGuide for add commands

---

docs/DeveloperGuide.md

Add target user profile, value proposition and user stories to DG

---

docs/UserGuide.md

Update User Guide for Delete and Clear commands

---

docs/team/rycs2812.md

Add skeletal-ppp for rycs2812

---

docs/UserGuide.md

Update User Guide for List commands

---

docs/UserGuide.md

Update UserGuide for mastery check commands

---

docs/UserGuide.md

- Add documentation for `mark`
- Add documentation for `unmark`
Fixes #41

Update User Guide for Mark commands

---

docs/DeveloperGuide.md

Update non-functionality requirements in DeveloperGuide

---

docs/DeveloperGuide.md

- Abstract out UI portions in MSS and Extensions
- Replace `user` with `Avenger`
Resolves #20

Edit Developer Guide use cases

---

src/main/java/jarvis/logic/commands/AddStudentCommand.java
src/main/java/jarvis/logic/commands/AddTaskCommand.java

- Change the displayed list to student list when `addstudent` is called and task list when `addtask` is called

Fix add commands

---

src/main/java/jarvis/logic/parser/ParserUtil.java
src/main/java/jarvis/model/TaskDesc.java

Task description is now required to be non empty.

Fix task description

---

build.gradle
src/main/java/jarvis/MainApp.java

- Enable assertions in `build.gradle`
- Update version number to v1.2.1 for trial JAR release

Enable assertions

---

src/main/java/jarvis/commons/core/Messages.java
src/main/java/jarvis/logic/commands/AddNoteCommand.java
src/main/java/jarvis/logic/commands/AddParticipationCommand.java
src/main/java/jarvis/logic/commands/DeleteNoteCommand.java
src/main/java/jarvis/logic/commands/MarkStudentCommand.java
src/main/java/jarvis/logic/commands/UnmarkStudentCommand.java
src/main/java/jarvis/logic/parser/CliSyntax.java
src/main/java/jarvis/logic/parser/DeleteNoteCommandParser.java
src/main/java/jarvis/logic/parser/JarvisParser.java
src/main/java/jarvis/model/Lesson.java
src/main/java/jarvis/model/LessonNotes.java
src/main/java/jarvis/model/exceptions/NoteNotFoundException.java

- Implement error handling for StudentNotFoundException for AddParticipationCommand, MarkStudentCommand, UnmarkStudentCommand and AddNoteCommand
- Refactor use of StringBuilder to ArrayList for storing overall notes and student notes
- Implement DeleteNoteCommand

Implement DeleteNoteCommand

---

src/main/java/jarvis/logic/commands/AddStudentCommand.java
src/main/java/jarvis/model/StudentBook.java
src/main/java/jarvis/model/UniqueStudentList.java
src/main/java/jarvis/model/exceptions/DuplicateLessonException.java
src/main/java/jarvis/model/exceptions/DuplicateStudentException.java
src/main/java/jarvis/model/exceptions/MaxStudentsExceededException.java

Set limit for number of students to 10.
`AddStudentCommand` will throw a `CommandException` with message stating the maximum number of students if user tries to add a student when there are already 10 students
Closes #102

Set limit for number of students

---

docs/index.md
src/main/java/jarvis/model/TimePeriod.java

- Update index.md
- Update error message for TimePeriod
Error message might not be clear enough in some cases. 
e.g 2022-13-32 would result in an error message asking for yyyy-MM-dd format
Maybe yyyy-MM-dd and hh:mm already implies the values should be in valid range but I think it would be less confusing this way for the users.

Update index.md and error message for TimePeriod

---

docs/UserGuide.md

- Add a tip to differentiate students with the same name in UG
closes #145

Fix issues mentioned in PED

---

docs/team/rachaelsng.md

- Updated PPP for the early draft

Draft the PPP

---

docs/UserGuide.md

Reverts AY2223S1-CS2103T-T11-3/tp#153
UG not rendered properly.

Revert "Fix issues mentioned in PED"

---

docs/UserGuide.md

- Add explanation for purpose of guide, how to use guide, basics of JARVIS
- Change basic/student/task/lesson "features" to basic/student/task/lesson "commands"

Update front matters for UG

---

docs/UserGuide.md

- Add tip in UG for students with similar names
closes #145

Fix issue from PE-D

---

docs/DeveloperGuide.md

Features added to DG appendix:
- set mc result
- add/delete note
- add participation

Add features to DG appendix

---

docs/UserGuide.md

- Add more explanations for some command descriptions
- Incorporate you-language
- Add meanings of syntax/icons used
- Put some chunks of text in "Note:" format
- Add instructions for checking Java version and downloading Java

Update UG for CS2101

---

docs/UserGuide.md

Attempt to remove table of contents header to prevent it from appearing in contents page

Fix table of contents header
